-- Verified public CNC papers (each PDF opened and its header checked): cpgemaroc.com physics/chemistry 2010–2025, rtc.ma SI/GE/GM/informatique 2012–2020. Idempotent.
insert into public.cnc_exams (id,filiere,subject,year,subject_url,correction_url,source_url,source_label,published)
select gen_random_uuid(),v.f,v.s,v.y,v.su,v.cu,v.src,v.lbl,true from (values
('MP','Physique I',2010,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2010.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2010.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2011,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2011.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2011.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2012,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2012.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2012.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2013,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2013.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2013.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2014,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2015,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2015.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2015.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2016,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2016.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2016.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2017,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2017.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2017.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2018,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2018.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2018.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2019,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2019.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2019.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2020,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2020.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2021,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2021.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2022,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2022.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c2_ph1mp2022.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2023,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2023.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2024,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2024.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2024.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique I',2025,'https://www.cpgemaroc.com/cnc/ph1mp/e_ph1mp2025.pdf','https://www.cpgemaroc.com/cnc/ph1mp/c_ph1mp2025.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2010,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2010.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2010.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2011,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2011.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2011.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2012,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2012.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2012.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2013,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2013.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2014,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2015,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2015.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c2_ph2mp2015.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2016,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2016.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2016.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2017,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2017.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2017.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2018,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2018.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2018.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2019,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2019.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2019.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2021,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2021.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2021.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2022,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2022.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2022.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2023,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2023.pdf','https://www.cpgemaroc.com/cnc/ph2mp/c_ph2mp2023.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2024,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Physique II',2025,'https://www.cpgemaroc.com/cnc/ph2mp/e_ph2mp2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2010,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2010.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2011,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2011.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2011.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2012,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2012.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2013,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2013.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2013.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2014,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2014.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2014.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2015,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2015.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2016,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2016.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2017,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2017.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2017.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2018,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2018.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2018.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2019,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2019.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2019.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2020,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2020.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2020.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2021,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2021.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2021.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2022,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2022.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2022.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2023,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2023.pdf','https://www.cpgemaroc.com/cnc/chmp/c_chmp2023.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2024,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Chimie',2025,'https://www.cpgemaroc.com/cnc/chmp/e_chmp2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2010,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2010.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2011,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2011.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2012,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2012.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2013,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2013.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2014,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2015,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2015.pdf','https://www.cpgemaroc.com/cnc/ph1psi/c_ph1psi2015.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2016,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2016.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2017,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2017.pdf','https://www.cpgemaroc.com/cnc/ph1psi/c_ph1psi2017.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2018,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2018.pdf','https://www.cpgemaroc.com/cnc/ph1psi/c_ph1psi2018.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2019,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2019.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2021,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2021.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2022,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2022.pdf','https://www.cpgemaroc.com/cnc/ph1psi/c_ph1psi2022.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2023,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2023.pdf','https://www.cpgemaroc.com/cnc/ph1psi/c_ph1psi2023.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2024,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique I',2025,'https://www.cpgemaroc.com/cnc/ph1psi/e_ph1psi2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2011,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2011.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2012,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2012.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2013,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2013.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2014,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2015,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2015.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2016,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2016.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2017,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2017.pdf','https://www.cpgemaroc.com/cnc/ph2psi/c_ph2psi2017.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2018,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2018.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2019,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2019.pdf','https://www.cpgemaroc.com/cnc/ph2psi/c_ph2psi2019.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2021,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2021.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2022,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2022.pdf','https://www.cpgemaroc.com/cnc/ph2psi/c_ph2psi2022.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2023,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2023.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2024,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Physique II',2025,'https://www.cpgemaroc.com/cnc/ph2psi/e_ph2psi2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2010,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2010.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2012,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2012.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2013,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2013.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2014,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2015,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2015.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2016,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2016.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2017,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2017.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2018,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2018.pdf','https://www.cpgemaroc.com/cnc/chpsi/c_chpsi2018.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2020,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2020.pdf','https://www.cpgemaroc.com/cnc/chpsi/c_chpsi2020.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2021,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2021.pdf','https://www.cpgemaroc.com/cnc/chpsi/c_chpsi2021.pdf','https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2022,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2022.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2023,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2023.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2024,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('PSI','Chimie',2025,'https://www.cpgemaroc.com/cnc/chpsi/e_chpsi2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2010,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2010.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2011,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2011.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2012,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2012.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2013,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2013.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2014,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2015,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2015.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2016,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2016.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2017,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2017.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2018,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2018.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2019,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2019.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2020,'https://www.cpgemaroc.com/cnc/ph1tsi/e_phtsi2020.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2021,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2021.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2022,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2022.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2023,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2023.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2024,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique I',2025,'https://www.cpgemaroc.com/cnc/ph1tsi/e_ph1tsi2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2011,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2011.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2012,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2012.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2013,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2013.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2014,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2015,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2015.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2016,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2016.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2017,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2017.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2018,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2018.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2019,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2019.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2021,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2021.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2022,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2022.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2023,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2023.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2024,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Physique II',2025,'https://www.cpgemaroc.com/cnc/ph2tsi/e_ph2tsi2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2010,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2010.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2011,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2011.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2012,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2012.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2013,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2013.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2014,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2014.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2015,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2015.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2017,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2017.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2018,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2018.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2019,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2019.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2020,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2020.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2021,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2021.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2022,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2022.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2023,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2023.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2024,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2024.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('TSI','Chimie',2025,'https://www.cpgemaroc.com/cnc/chtsi/e_chtsi2025.pdf',null,'https://www.cpgemaroc.com/','CPGE Maroc'),
('MP','Sciences industrielles',2012,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202012%20SI%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/si/CNC%202012%20SI%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2013,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202013%20SI%20MP.pdf',null,'https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2014,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202014%20SI%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/si/CNC%202014%20SI%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2015,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202015%20SI%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/si/CNC%202015%20SI%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2016,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202016%20SI%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/si/CNC%202016%20SI%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2017,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202017%20SI%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/si/CNC%202017%20SI%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2018,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202018%20SI%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/si/CNC%202018%20SI%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2019,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202019%20SI%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/si/CNC%202019%20SI%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Sciences industrielles',2020,'https://rtc.ma/pdfs/MP/cnc/si/CNC%202020%20SI%20MP.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Génie électrique',2012,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202012%20Ge%20TSI.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Génie électrique',2013,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202013%20Ge%20TSI.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Génie électrique',2016,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202016%20Ge%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202016%20Ge%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie électrique',2017,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202017%20Ge%20TSI.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Génie électrique',2018,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202018%20Ge%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202018%20Ge%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie électrique',2019,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202019%20Ge%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202019%20Ge%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie électrique',2020,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202020%20Ge%20TSI.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2012,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202012%20Gm%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202012%20Gm%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2013,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202013%20Gm%20TSI.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2015,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202015%20Gm%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202015%20Gm%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2016,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202016%20Gm%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202016%20Gm%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2017,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202017%20Gm%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202017%20Gm%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2018,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202018%20Gm%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202018%20Gm%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2019,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202019%20Gm%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/si/CNC%202019%20Gm%20Correction%20TSI.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Génie mécanique',2020,'https://rtc.ma/pdfs/TSI/cnc/si/CNC%202020%20Gm%20TSI.pdf',null,'https://rtc.ma/','rtc.ma'),
('MP','Informatique',2015,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202015.pdf',null,'https://rtc.ma/','rtc.ma'),
('PSI','Informatique',2015,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202015.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Informatique',2015,'https://rtc.ma/pdfs/TSI/cnc/info/CNC%20Info%202015.pdf',null,'https://rtc.ma/','rtc.ma'),
('MP','Informatique',2016,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202016.pdf',null,'https://rtc.ma/','rtc.ma'),
('PSI','Informatique',2016,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202016.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Informatique',2016,'https://rtc.ma/pdfs/TSI/cnc/info/CNC%20Info%202016.pdf',null,'https://rtc.ma/','rtc.ma'),
('MP','Informatique',2017,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202017.pdf','https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202017%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('PSI','Informatique',2017,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202017.pdf','https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202017%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('TSI','Informatique',2017,'https://rtc.ma/pdfs/TSI/cnc/info/CNC%20Info%202017.pdf','https://rtc.ma/pdfs/TSI/cnc/info/CNC%20Info%202017%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Informatique',2018,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202018%20MP.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Informatique',2018,'https://rtc.ma/pdfs/TSI/cnc/info/CNC%20Info%202018%20TSI.pdf','https://rtc.ma/pdfs/TSI/cnc/info/CNC%20Info%202018%20TSI%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Informatique',2019,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202019%20MP.pdf','https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202019%20MP%20Correction.pdf','https://rtc.ma/','rtc.ma'),
('MP','Informatique',2020,'https://rtc.ma/pdfs/MP/cnc/info/CNC%20Info%202020%20MP.pdf',null,'https://rtc.ma/','rtc.ma'),
('TSI','Informatique',2020,'https://rtc.ma/pdfs/TSI/cnc/info/CNC%20Info%202020%20TSI.pdf',null,'https://rtc.ma/','rtc.ma')
) as v(f,s,y,su,cu,src,lbl)
where not exists (select 1 from public.cnc_exams e where e.filiere=v.f and e.subject=v.s and e.year=v.y and not e.archived);
